Models/DbTick.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication8.Models
{
    public partial class DbTick
    {
        public int TickId { get; set; }
        [Display(Name = "反馈内容")]
        public string Ticking { get; set; }
        [Display(Name = "处理状态")]
        public string Handle { get; set; }
        [Display(Name = "更新状态")]
        public string Update { get; set; }
        [Display(Name = "反馈人")]
        public string EmName { get; set; }
        public int? QuId { get; set; }

        public DbQu Qu { get; set; }

    }
}

Controllers/DbTicksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication8.Models;

namespace WebApplication8.Controllers
{
    public class DbTicksController : FonourControllerBase
    {
        private readonly NEUContext _context;

        public DbTicksController(NEUContext context)
        {
            _context = context;
        }
        public IActionResult Do()
        {
            HttpContext.Session.Remove("string1");

            return Redirect("~/DbTicks/Create");
        }
        // GET: DbTicks
        public async Task<IActionResult> Index()
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);
            if (!dbem.PoId.Equals(1))
            {
                return Redirect("~/Login/Create");
            }
            var dbTick = from d in _context.DbTick.Include(e => e.Qu) where (d.Handle == "未处理") select d;
            //var nEUContext = _context.DbSc.Include(d => d.Bu).Include(d => d.Em);
          //  return View(await dbTick.ToListAsync());

            return View(dbTick);
        }

        // GET: DbTicks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dbTick = await _context.DbTick
                .SingleOrDefaultAsync(m => m.TickId == id);
            if (dbTick == null)
            {
                return NotFound();
            }

            return View(dbTick);
        }

        // GET: DbTicks/Create
        public async Task<IActionResult> Create(string searchString, int id = 1)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);
            if (!dbem.PoId.Equals(1))
            {
                return Redirect("~/Login/Create");
            }
            ViewBag.string1 = HttpContext.Session.GetString("string1");
            string string11 = ViewBag.string1;
            var dbTick = from d in _context.DbTick where (d.Handle == "已处理") select d;

            if (searchString != null)
            {
                HttpContext.Session.SetString("string1", searchString);

            }
            if (string11 != null)
            {
                ViewBag.string1 = HttpContext.Session.GetString("string1");
                string string2 = ViewBag.string1;
                searchString = string2;
                if (!String.IsNullOrEmpty(searchString))
                {
                    dbTick = dbTick.Where(s => s.Update.Contains(searchString));
                }
            }
            else
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    dbTick = dbTick.Where(s => s.Update.Contains(searchString));
                }
            }
        
            var pageOption = new MoPagerOption
            {
                CurrentPage = id,
                PageSize = 20,
                Total = await dbTick.CountAsync(),
                RouteUrl = "/DbTicks/Create"
            };


          
            //分页参数
            ViewBag.PagerOption = pageOption;
            // return View(movieGenreVM);
            return View(await dbTick.OrderByDescending(b => b.TickId).Skip((pageOption.CurrentPage - 1) * pageOption.PageSize).Take(pageOption.PageSize).ToListAsync());
            //var nEUContext = _context.DbSc.Include(d => d.Bu).Include(d => d.Em);
          
        }

        // GET: DbTicks/Edit/5
        public async Task<IActionResult> Edit(int? id,int ida)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);
            if (!dbem.PoId.Equals(1))
            {
                return Redirect("~/Login/Create");
            }
            if (id == null)
            {
                return NotFound();
            }
          
            HttpContext.Session.SetInt32("ida", ida);
            var dbTick=await _context.DbTick.SingleOrDefaultAsync(m => m.TickId == ida);
            var dbQu = await _context.DbQu.SingleOrDefaultAsync(m => m.QuId == id);
            if (dbQu == null)
            {
                return NotFound();
            }
            ViewData["BuId"] = new SelectList(_context.DbBu, "BuId", "BuName", dbQu.BuId);
            ViewData["SucId"] = new SelectList(_context.DbSu3, "SucId", "SucName", dbQu.SucId);
            return View(dbQu);
        }

        // POST: DbQus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("QuId,Type,BuId,Question,OptionA,OptionB,OptionC,OptionD,RightAnswer,Difficulty,SucId,EmId")] DbQu dbQu, [Bind("QuId,AlQuestion,AlOptionA,AlOptionB,AlOptionC,AlOptionD,AlRightAnswer,AlDifficulty,EmName,AlterTime,AlEdit")] DbLog dbLog)
        {

            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);

            if (!dbem.PoId.Equals(1))
            {
                return Redirect("~/Login/Create");
            }
            if (id != dbQu.QuId)
            {
                return NotFound();
            }
          
            ViewBag.ida = HttpContext.Session.GetInt32("ida");
            
            int ida = ViewBag.ida;
            DbTick dbtick=new DbTick();
            var dbqu = await _context.DbQu.SingleOrDefaultAsync(m => m.QuId == id);
            dbtick= await _context.DbTick.SingleOrDefaultAsync(m => m.TickId == ida);
    
         //   Type,BuId,Question,OptionA,OptionB,OptionC,OptionD,RightAnswer,Difficulty,SucId,
            if (dbQu.Type!=dbqu.Type||dbQu.BuId!=dbqu.BuId || dbQu.Question != dbqu.Question || dbQu.OptionA != dbqu.OptionA || dbQu.OptionB != dbqu.OptionB || dbQu.OptionC != dbqu.OptionC || dbQu.OptionD != dbqu.OptionD || dbQu.Difficulty != dbqu.Difficulty||dbQu.RightAnswer!=dbqu.RightAnswer)
            {
                dbLog.QuId = dbqu.QuId;
                dbLog.AlDifficulty = dbqu.Difficulty;
                dbLog.AlQuestion = dbqu.Question;
                dbLog.AlOptionA = dbqu.OptionA;
                dbLog.AlOptionB = dbqu.OptionB;
                dbLog.AlOptionC = dbqu.OptionC;
                dbLog.AlOptionD = dbqu.OptionD;
                dbLog.AlRightAnswer = dbqu.RightAnswer;
                dbLog.AlterTime = DateTime.Now;
                dbLog.EmName = dbem.EmName;
                dbLog.AlEdit = "修改";                
                dbtick.Update = "已更新";
                _context.Add(dbLog);
            }
            dbtick.Handle = "已处理";
            dbtick.Update = "未更新";

            dbqu.Type = dbQu.Type;
            dbqu.BuId = dbQu.BuId;
            dbqu.Question = dbQu.Question;
            dbqu.OptionA = dbQu.OptionA;
            dbqu.OptionB = dbQu.OptionB;
            dbqu.OptionC = dbQu.OptionC;
            dbqu.OptionD = dbQu.OptionD;
            dbqu.RightAnswer = dbQu.RightAnswer;
            dbqu.SucId = dbQu.SucId;
            dbqu.Difficulty = dbQu.Difficulty;
            dbqu.EmId = Eid;
            _context.Update(dbtick);
           
            _context.Update(dbqu);
            await _context.SaveChangesAsync();
            //HttpContext.Session.Remove("ida");
            return RedirectToAction(nameof(Index));
        }


        // GET: DbTicks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dbTick = await _context.DbTick
                .SingleOrDefaultAsync(m => m.TickId == id);
            if (dbTick == null)
            {
                return NotFound();
            }

            return View(dbTick);
        }

        // POST: DbTicks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dbTick = await _context.DbTick.SingleOrDefaultAsync(m => m.TickId == id);
            _context.DbTick.Remove(dbTick);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DbTickExists(int id)
        {
            return _context.DbTick.Any(e => e.TickId == id);
        }
    }
}

Views/DbTicks/Create.cshtml
@model IEnumerable<WebApplication8.Models.DbTick>

@{
    ViewData["Title"] = "Create";
}
@{
    Layout = "_Layout_paperadmin";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">试题管理</a>
                </li>
                <li class="active">试题管理</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->
<h2>题目反馈</h2>
<form asp-controller="DbTicks" asp-action="Create">
    <p>
        更新状态: <select name="searchString">
            <option value="已更新">已更新</option>
            <option value="未更新">未更新</option>
        </select>
        <input type="submit" value="查询" /><a asp-action="Do">条件消除</a>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ticking)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Handle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Update)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ticking)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Handle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Update)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmName)
                </td>
                <td>
                   @* <a asp-action="Edit" asp-route-id="@item.QuId" asp-route-ida="@item.TickId">编辑</a>*@
                    <a asp-action="Edit" asp-route-id="@item.QuId" class="tooltip-success" data-rel="tooltip" title="Edit">
                        <span class="green">
                            <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    <a asp-controller="DbTicks" asp-action="Index">返回主页</a>
</p>
<pager pager-option="ViewBag.PagerOption as MoPagerOption"></pager>

Views/DbTicks/Delete.cshtml
@model WebApplication8.Models.DbTick

@{
    ViewData["Title"] = "Delete";
}
@{
    Layout = "_Layout_paperadmin";
}
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">试题管理</a>
                </li>
                <li><a asp-area="" asp-controller="DbTicks" asp-action="Index">题目反馈</a></li>
                <li class="active">反馈信息删除</li>

            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->


<h3>确定要删除反馈意见吗?</h3>
<div>
    <h4>DbTick</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ticking)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ticking)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Handle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Handle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Update)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Update)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuId)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="TickId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">反馈题目反馈</a>
    </form>
</div>

Views/DbTicks/Details.cshtml
@model WebApplication8.Models.DbTick

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>DbTick</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ticking)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ticking)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Handle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Handle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Update)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Update)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.QuId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TickId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/DbTicks/Edit.cshtml
@model WebApplication8.Models.DbQu

@{
    ViewData["Title"] = "Edit";
}

@{
    Layout = "_Layout_paperadmin";
}
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">试题管理</a>
                </li>
                <li><a asp-area="" asp-controller="DbTicks" asp-action="Index">题目反馈</a></li>
                <li class="active">反馈题目编辑</li>

            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="QuId" />
            <div class="form-group">
                <label asp-for="Type" class="control-label">题型</label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BuId" class="control-label">职位</label>
                <select asp-for="BuId" class="form-control" asp-items="ViewBag.BuId"></select>
                <span asp-validation-for="BuId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Question" class="control-label">题目</label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionA" class="control-label">A</label>
                <input asp-for="OptionA" class="form-control" />
                <span asp-validation-for="OptionA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionB" class="control-label">B</label>
                <input asp-for="OptionB" class="form-control" />
                <span asp-validation-for="OptionB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionC" class="control-label">C</label>
                <input asp-for="OptionC" class="form-control" />
                <span asp-validation-for="OptionC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OptionD" class="control-label">D</label>
                <input asp-for="OptionD" class="form-control" />
                <span asp-validation-for="OptionD" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RightAnswer" class="control-label">正确答案</label>
                <input asp-for="RightAnswer" class="form-control" />
                <span asp-validation-for="RightAnswer" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SucId" class="control-label">专业</label>
                <select asp-for="SucId" class="form-control" asp-items="ViewBag.SucId"></select>
                <span asp-validation-for="BuId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Difficulty" class="control-label">难度</label>
                <input asp-for="Difficulty" class="form-control" />
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="保存" class="btn btn-lg btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">返回题库</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DbTicks/Index.cshtml
@model IEnumerable<WebApplication8.Models.DbTick>

@{
    ViewData["Title"] = "Index";
}
@{
    Layout = "_Layout_paperadmin";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">试题管理</a>
                </li>
                <li class="active">试题反馈</li>
            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->
<p>

    <a asp-action="Create" class="btn btn-primary btn-flat btn-addon m-b-10 m-l-5"><i class="ti-plus"></i>查看处理记录</a>

</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ticking)
            </th>
            <th>
                题目
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Handle)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.EmName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ticking)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Qu.Question)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Handle)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.EmName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.QuId" class="tooltip-success" data-rel="tooltip" title="Edit">
                        <span class="green">
                            <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                        </span>
                    </a>
                    @*<a asp-action="Edit" asp-route-id="@item.QuId" asp-route-ida="@item.TickId">编辑</a>*@

                </td>
            </tr>
        }
    </tbody>
</table>