Models/DbPax.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace WebApplication8.Models
{
    public partial class DbPax
    {
        public DbPax()
        {
            DbTe = new HashSet<DbTe>();
        }
        
        public int Pax1_ID { get; set; }//试卷题号
        public int PaxId { get; set; }//主键
        public int QuId { get; set; }
        public int PaId { get; set; }
        [Display(Name = "题号")]       
        public DbPa Pa { get; set; }
        public DbQu Qu { get; set; }
        public ICollection<DbTe> DbTe { get; set; }
    }
}

Controllers/DbPaxesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using WebApplication8.Models;

namespace WebApplication8.Controllers
{
    public class DbPaxesController : Controller
    {
        private readonly NEUContext _context;
        private int tureOrFalseNum = 10;//判断题数量
        private int singleCho = 20;//单选题数量
        private int multipleCho = 10;//多选题数量
        private static DateTime testStart;
        private static DateTime testEnd;
        private static int signTime;



        public DbPaxesController(NEUContext context)
        {

            _context = context;
        }

        private bool QuestionExists(Int32 id, List<int> value)
        {
            foreach (var item in value)
            {
                if (item == id) return true;

                else
                {
                    continue;
                }
            }
            return false;

        }



        public static Dictionary<int, int> pax_list = new Dictionary<int, int>();
        public static Dictionary<int, string> ans_list = new Dictionary<int, string>();
        // GET: DbPaxes
        public async Task<IActionResult> Index()
        {
            pax_list.Clear();
            ans_list.Clear();

            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            if (ViewBag.UserId == null)
            {
                return RedirectToAction("Create", "DbEms");
            }

            //var selId_3 = HttpContext.Session.GetInt32("selId_3");
            //var selId_2 = HttpContext.Session.GetInt32("selId_2");
            var selId_1 = HttpContext.Session.GetInt32("selId_1");

            //生成试卷号


            IQueryable<DbQu> qu;
            //根据专业抽题
            //var select3 = HttpContext.Session.GetString("select3");
            //var select2 = HttpContext.Session.GetString("select2");
            var select1 = HttpContext.Session.GetString("select1");
            //if (select3 != null)
            //{
            //    var sel = await _context.DbSu3.SingleOrDefaultAsync(d => d.SucName.Equals(select3));
            //    qu = from d in _context.DbQu where (d.SucId == sel.SucId) select d;

            //}
            //else if (select2 != null)
            //{
            //    var sel = await _context.DbSu2.SingleOrDefaultAsync(d => d.SubName.Equals(select2));
            //    qu = from d in _context.DbQu where (d.SubId == sel.SubId) select d;

            //}
            //else 
            if (select1 != null)
            {
                var sel = await _context.DbSu1.SingleOrDefaultAsync(d => d.SuaName.Equals(select1));
                qu = from d in _context.DbQu where (d.SuaId == sel.SuaId) select d;
                if(qu.Count()==0)
                {
                    HttpContext.Session.SetInt32("Sign", 1);
                    return RedirectToAction("Start", "DbEms");
                }

            }
            else
            {
                HttpContext.Session.SetInt32("Sign", 0);
                qu = from d in _context.DbQu select d;
            }


            //从抽出的该专业的题中抽取不同难度的单选题和多选题
            int j = 1;

            var single_Choice = from d in qu where (d.Type.Equals("单选")) select d;
            //int m = single_Choice.Count();
            var multiple_Choice = from d in qu where (d.Type.Equals("多选")) select d;
            var trueOrFalse = from d in qu where (d.Type.Equals("判断")) select d;

            List<int> keys = new List<int>();
            List<int> value = new List<int>();


            var hardT = from d in trueOrFalse where (d.Difficulty.Equals("难")) select d;
            for (int i = 0; i < tureOrFalseNum * 0.2;)
            {


                DbPax dbPax = new DbPax();
                Random s = new Random();
                var cc = hardT.ToList();
                int b = s.Next(0, hardT.Count());
                if (!QuestionExists(cc[b].QuId, value))//试卷中不存在新抽取的题，将其加入试卷
                {
                    j++;

                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }

            }

            var mediumT = from d in trueOrFalse where (d.Difficulty.Equals("中")) select d;
            for (int i = 0; i < tureOrFalseNum * 0.5;)
            {
                DbExam dbExam = new DbExam();
                DbPax dbPax = new DbPax();

                Random s = new Random();
                var cc = mediumT.ToList();

                int b = s.Next(0, mediumT.Count());
                if (!QuestionExists(cc[b].QuId, value))
                {

                    j++;
                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }

            }

            var simpleT = from d in trueOrFalse where (d.Difficulty.Equals("易")) select d;
            for (int i = 0; i < tureOrFalseNum * 0.3;)
            {

                DbExam dbExam = new DbExam();

                Random s = new Random();
                var cc = simpleT.ToList();
                DbPax dbPax = new DbPax();
                int b = s.Next(0, simpleT.Count());
                if (!QuestionExists(cc[b].QuId, value))
                {
                    j++;

                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }
            }

            var hardS = from d in single_Choice where (d.Difficulty.Equals("难")) select d;
            for (int i = 0; i < singleCho * 0.2;)
            {


                DbPax dbPax = new DbPax();
                Random s = new Random();
                var cc = hardS.ToList();
                int b = s.Next(0, hardS.Count());
                if (!QuestionExists(cc[b].QuId, value))//试卷中不存在新抽取的题，将其加入试卷
                {
                    j++;

                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }

            }

            var mediumS = from d in single_Choice where (d.Difficulty.Equals("中")) select d;
            for (int i = 0; i < singleCho * 0.5;)
            {
                DbExam dbExam = new DbExam();
                DbPax dbPax = new DbPax();

                Random s = new Random();
                var cc = mediumS.ToList();

                int b = s.Next(0, mediumS.Count());
                if (!QuestionExists(cc[b].QuId, value))
                {

                    j++;
                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }

            }

            var simpleS = from d in single_Choice where (d.Difficulty.Equals("易")) select d;
            for (int i = 0; i < singleCho * 0.3;)
            {

                DbExam dbExam = new DbExam();

                Random s = new Random();
                var cc = simpleS.ToList();
                DbPax dbPax = new DbPax();
                int b = s.Next(0, simpleS.Count());
                if (!QuestionExists(cc[b].QuId, value))
                {
                    j++;

                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }
            }

            var hardM = from d in multiple_Choice where (d.Difficulty.Equals("难")) select d;
            for (int i = 0; i < multipleCho * 0.2;)
            {

                DbPax dbPax = new DbPax();

                Random s = new Random();
                var cc = hardM.ToList();

                int b = s.Next(0, hardM.Count());
                if (!QuestionExists(cc[b].QuId, value))
                {
                    j++;

                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }
            }
            for (int i = 0; i < multipleCho * 0.5;)
            {
                DbExam dbExam = new DbExam();
                DbPax dbPax = new DbPax();
                var mediumM = from d in multiple_Choice where (d.Difficulty.Equals("中")) select d;
                Random s = new Random();
                var cc = mediumM.ToList();

                int b = s.Next(0, mediumM.Count());
                if (!QuestionExists(cc[b].QuId, value))
                {
                    j++;

                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }
            }
            for (int i = 0; i < multipleCho * 0.3;)
            {
                DbExam dbExam = new DbExam();
                DbPax dbPax = new DbPax();
                var simpleM = from d in multiple_Choice where (d.Difficulty.Equals("易")) select d;
                Random s = new Random();
                var cc = simpleM.ToList();

                int b = s.Next(0, simpleM.Count());
                if (!QuestionExists(cc[b].QuId, value))
                {
                    j++;

                    pax_list.Add(j - 1, cc[b].QuId);
                    keys.Add(j - 1);
                    value.Add(cc[b].QuId);

                    ++i;
                }
            }


            DbPa dbpa = new DbPa();

            dbpa.EmId = ViewBag.UserId;
            dbpa.SuaId = selId_1;
            //dbpa.SubId = selId_2;
            //dbpa.SucId = selId_3;
            _context.DbPa.Add(dbpa);

Views/DbPaxes/Create.cshtml
@model WebApplication8.Models.DbPax
@{
    Layout = "_Layout_practice";

}
@{
    ViewData["Title"] = "Create";
    string answer = null;
    if (ViewData["ans"] != null)
    {
        var ans = ViewData["ans"];
        answer = ans.ToString();

    }
}

@{
    if (ViewData["ErrorSign"] != null)
    {

        <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
        <script type="text/javascript" language="javascript">
            $(document).ready(function () {

                alert("请作答当前试题");

            });
        </script>
    }
}
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">模拟答题</a>
                </li>

                <li class="active">多选</li>

            </ul><!-- /.breadcrumb -->


        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->


<hr />
<form asp-controller="DbPaxes" asp-action="Create">
    <p>
        题目反馈: <input type="text" name="SearchString">
        <input type="submit" value="反馈" />
    </p>

</form>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PaxId" />
            <table>
                <tr>
                    <td>
                        <input type="hidden" id="num" asp-for="Pax1_ID" />
                    </td>

                    <td></td>
                </tr>
                <tr>

                    <td width="80px" valign="top">
                        （多选)@Html.DisplayFor(modelItem => Model.Pax1_ID) .

                    </td>
                    <td>@Html.DisplayFor(modelItem => modelItem.Qu.Question)</td>
                </tr>
                @{
                    if (answer == null)
                    {

                        <tr>

                            <td style="text-align:center"><input type="checkbox" id="ch_1" Name="checkBox" value="A" /></td>
                            <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                        </tr>
                        <tr>

                            <td style="text-align:center"><input type="checkbox" id="ch_2" Name="checkBox" value="B" /></td>
                            <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                        </tr>
                        <tr>

                            <td style="text-align:center"><input type="checkbox" id="ch_3" Name="checkBox" value="C" /></td>
                            <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                        </tr>
                        <tr>
                            <td style="text-align:center"><input type="checkbox" id="ch_4" Name="checkBox" value="D" /></td>
                            <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                        </tr>

                    }
                    else
                    {
                        string[] a = answer.Split(",");

                        if (a.Contains("A"))
                        {
                            <tr>

                                <td style="text-align:center"><input type="checkbox" id="ch_1" Name="checkBox" value="A" checked="checked" /></td>
                                <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                            </tr>
                        }
                        else
                        {
                            <tr>

                                <td style="text-align:center"><input type="checkbox" id="ch_1" Name="checkBox" value="A" /></td>
                                <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                            </tr>

                        }
                        if (a.Contains("B"))
                        {
                            <tr>

                                <td style="text-align:center"><input type="checkbox" id="ch_2" Name="checkBox" value="B" checked="checked" /></td>
                                <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                            </tr>

                        }
                        else
                        {
                            <tr>

                                <td style="text-align:center"><input type="checkbox" id="ch_2" Name="checkBox" value="B" /></td>
                                <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                            </tr>

                        }
                        if (a.Contains("C"))
                        {
                            <tr>

                                <td style="text-align:center"><input type="checkbox" id="ch_3" Name="checkBox" value="C" checked="checked" /></td>
                                <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                            </tr>
                        }
                        else
                        {
                            <tr>

                                <td style="text-align:center"><input type="checkbox" id="ch_3" Name="checkBox" value="C" /></td>
                                <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                            </tr>

                        }
                        if (a.Contains("D"))
                        {
                            <tr>
                                <td style="text-align:center"><input type="checkbox" id="ch_4" Name="checkBox" value="D" checked="checked" /></td>
                                <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                            </tr>

                        }
                        else
                        {
                            <tr>
                                <td style="text-align:center"><input type="checkbox" id="ch_4" Name="checkBox" value="D" /></td>
                                <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                            </tr>

                        }



                    }

                }

            </table>
            <div class="form-group">
                <input type="submit" value="上一题" class="btn btn-default" name="edit" />
                <input type="submit" id="sub" value="下一题" class="btn btn-default" name="edit" />
            </div>

        </form>
    </div>
</div>
<div>
    <a asp-action="Details">返回题目列表</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript">
    $(document).ready(function () {

        $("#sub").click(function () {

            if ($("#num").val() == "40") {
                if (confirm("确认提交试卷？")) {

                }
                else {

                }

            }
        });

    });
</script>

Views/DbPaxes/Edit.cshtml
@model WebApplication8.Models.DbPax
@{
    Layout = "_Layout_practice";
}
@{
    ViewData["Title"] = "Edit";
    string answer = null;
    if (ViewData["ans"] != null)
    {
        var ans = ViewData["ans"];
        answer = ans.ToString();

    }
}
@{
    if (ViewData["ErrorSign"] != null)
    {

        <script src="~/lib/jquery/dist/jquery.js" type="text/javascript"></script>
        <script type="text/javascript" language="javascript">
            $(document).ready(function () {

                alert("请作答当前试题");

            });
        </script>
    }
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">模拟答题</a>
                </li>

                <li class="active">单选</li>

            </ul><!-- /.breadcrumb -->


        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->



<h4></h4>
<hr />

<form asp-controller="DbPaxes" asp-action="Edit">
    <p>
        题目反馈: <input type="text" name="SearchString">
        <input type="submit" value="反馈" />
    </p>
</form>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PaxId" />
            @if (Model.Qu.Type.Equals("判断"))
            {
                <table>
                    <tr>

                        <td width="80px" valign="top">（判断）@Html.DisplayFor(modelItem => Model.Pax1_ID) .</td>
                        <td>@Html.DisplayFor(modelItem => modelItem.Qu.Question)</td>
                    </tr>
                    @{
                        if (answer == null)
                        {
                            <tr>

                                <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" /></td>
                                <td>@Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                            </tr>
                            <tr>

                                <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" /></td>
                                <td>@Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                            </tr>

                        }
                        else
                        {
                            if (answer == "A")
                            {
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" checked="checked" /></td>
                                    <td>@Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" /></td>
                                    <td>@Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                                </tr>

                            }
                            if (answer == "B")
                            {
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" /></td>
                                    <td>@Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" checked="checked" /></td>
                                    <td>@Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                                </tr>

                            }



                        }
                    }

                </table>


            }
            else
            {
                <table>
                    <tr>

                        <td width="80px" valign="top">（单选）@Html.DisplayFor(modelItem => Model.Pax1_ID) .</td>
                        <td>@Html.DisplayFor(modelItem => modelItem.Qu.Question)</td>
                    </tr>

                    @{if (answer == null)
                        {
                            <tr>

                                <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" /></td>
                                <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                            </tr>
                            <tr>

                                <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" /></td>
                                <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                            </tr>
                            <tr>

                                <td style="text-align:center"><input type="radio" id="ra_3" Name="Option" value="C" /></td>
                                <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                            </tr>
                            <tr>

                                <td style="text-align:center"><input type="radio" id="ra_4" Name="Option" value="D" /></td>
                                <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                            </tr>


                        }
                        else
                        {
                            if (answer == "A")
                            {
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" checked="checked" /></td>
                                    <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" /></td>
                                    <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_3" Name="Option" value="C" /></td>
                                    <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_4" Name="Option" value="D" /></td>
                                    <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                                </tr>

                            }
                            if (answer == "B")
                            {
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" /></td>
                                    <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" checked="checked" /></td>
                                    <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_3" Name="Option" value="C" /></td>
                                    <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_4" Name="Option" value="D" /></td>
                                    <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                                </tr>

                            }
                            if (answer == "C")
                            {
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" /></td>
                                    <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" /></td>
                                    <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_3" Name="Option" value="C" checked="checked" /></td>
                                    <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_4" Name="Option" value="D" /></td>
                                    <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                                </tr>

                            }
                            if (answer == "D")
                            {
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_1" Name="Option" value="A" /></td>
                                    <td>A. @Html.DisplayFor(modelItem => Model.Qu.OptionA)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_2" Name="Option" value="B" /></td>
                                    <td>B. @Html.DisplayFor(modelItem => Model.Qu.OptionB)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_3" Name="Option" value="C" /></td>
                                    <td>C. @Html.DisplayFor(modelItem => Model.Qu.OptionC)</td>
                                </tr>
                                <tr>

                                    <td style="text-align:center"><input type="radio" id="ra_4" Name="Option" value="D" checked="checked" /></td>
                                    <td>D. @Html.DisplayFor(modelItem => Model.Qu.OptionD)</td>
                                </tr>

                            }

                        }
                    }

                </table>

            }




            <div class="form-group">
                <input type="submit" value="上一题" id="theLast" class="btn btn-default" name="edit" />
                <input type="submit" value="下一题" id="theNext" class="btn btn-default" name="edit" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details">返回题目列表</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


        
   

Views/DbPaxes/Time.cshtml
<script src="~/js/jquery-2.2.3.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        var now = new Date();
        var end = new Date();
        end.setHours(end.getHours() + 1);//结束的时间：年，月，日，分，秒（月的索引是0~11）
        /*两个时间相减,得到的是毫秒ms,变成秒*/
        var result = Math.floor(end - now) / 1000;

        var interval = setInterval(sub, 1000); //定时器 调度对象
        /*封装减1秒的函数*/
        function sub() {
            if (result > 1) {
                result = result - 1;
                var second = Math.floor(result % 60);     // 计算秒 ，取余
                var minite = Math.floor((result / 60) % 60); //计算分 ，换算有多少分，取余，余出多少秒
                var hour = Math.floor((result / 3600) % 24); //计算小时，换算有多少小时，取余，24小时制除以24，余出多少小时
                //var day = Math.floor(result / (3600 * 24));  //计算天 ，换算有多少天

                $("#remainTime").html(hour + ":" + minite + ":" + second);
            } else {
                alert("倒计时结束！");
                window.clearInterval(interval);//这里可以添加倒计时结束后需要执行的事件
            }
        };
    });
</script>