Models/DbBu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication8.Models
{
    public partial class DbBu
    {
        public DbBu()
        {
            DbEm = new HashSet<DbEm>();
            DbQu = new HashSet<DbQu>();
            TeSc = new HashSet<TeSc>();
            DbSc = new HashSet<DbSc>();
        }

        public int BuId { get; set; }
        [Display(Name = "职位")]
        public string BuName { get; set; }

        public ICollection<DbEm> DbEm { get; set; }
        public ICollection<DbQu> DbQu { get; set; }
        public ICollection<DbSc> DbSc { get; set; }
        public ICollection<TeSc> TeSc { get; set; }
    }
}

Controllers/DbBusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication8.Models;

namespace WebApplication8.Controllers
{
    public class DbBusController : FonourControllerBase
    {
        private readonly NEUContext _context;

        public DbBusController(NEUContext context)
        {
            _context = context;
        }

        // GET: DbBus
        public async Task<IActionResult> Index()
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(4))
            {
                return Redirect("~/DbEms/Create");
            }
            return View(await _context.DbBu.ToListAsync());
        }

        // GET: DbBus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(4))
            {
                return Redirect("~/DbEms/Create");
            }
            if (id == null)
            {
                return NotFound();
            }

            var dbBu = await _context.DbBu
                .SingleOrDefaultAsync(m => m.BuId == id);
            if (dbBu == null)
            {
                return NotFound();
            }

            return View(dbBu);
        }

        // GET: DbBus/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(1))
            {
                //return Redirect("~/DbEms/Create");
            }
            return View();
        }

        // POST: DbBus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BuId,BuName")] DbBu dbBu)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(4))
            {
                return Redirect("~/DbEms/Create");
            }
            if (ModelState.IsValid)
            {
                _context.Add(dbBu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dbBu);
        }

        // GET: DbBus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(4))
            {
                return Redirect("~/DbEms/Create");
            }
            if (id == null)
            {
                return NotFound();
            }

            var dbBu = await _context.DbBu.SingleOrDefaultAsync(m => m.BuId == id);
            if (dbBu == null)
            {
                return NotFound();
            }
            return View(dbBu);
        }

        // POST: DbBus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BuId,BuName")] DbBu dbBu)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(4))
            {
                return Redirect("~/DbEms/Create");
            }
            if (id != dbBu.BuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dbBu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DbBuExists(dbBu.BuId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dbBu);
        }

        // GET: DbBus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(4))
            {
                return Redirect("~/DbEms/Create");
            }
            if (id == null)
            {
                return NotFound();
            }

            var dbBu = await _context.DbBu
                .SingleOrDefaultAsync(m => m.BuId == id);
            if (dbBu == null)
            {
                return NotFound();
            }

            return View(dbBu);
        }

        // POST: DbBus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewBag.UserId = HttpContext.Session.GetInt32("UserId");
            DbEm dbem = new DbEm();
            int Eid = ViewBag.UserId;
            dbem = await _context.DbEm.SingleOrDefaultAsync(d => d.EmId == Eid);


            //var PoName = from d in _context.DbPo where (d.PoId == dbem.EmId) select d;
            if (!dbem.PoId.Equals(4))
            {
                return Redirect("~/DbEms/Create");
            }
            var dbBu = await _context.DbBu.SingleOrDefaultAsync(m => m.BuId == id);
            _context.DbBu.Remove(dbBu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DbBuExists(int id)
        {
            return _context.DbBu.Any(e => e.BuId == id);
        }
    }
}

Views/DbBus/Create.cshtml
@model WebApplication8.Models.DbBu
@{
    Layout = "_Layout_admin";
}
@{
    ViewData["Title"] = "Create";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">系统管理</a>
                </li>
                <li><a asp-area="" asp-controller="DbBus" asp-action="Index">岗位管理</a></li>
                <li class="active">添加新岗位</li>

            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BuName" class="control-label"></label>
                <input asp-for="BuName" class="form-control" />
                <span asp-validation-for="BuName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="添加" class="btn btn-lg btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">职位管理</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DbBus/Delete.cshtml
@model WebApplication8.Models.DbBu
@{
    Layout = "_Layout_admin";
}
@{
    ViewData["Title"] = "Delete";
}
<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">系统管理</a>
                </li>
                <li><a asp-area="" asp-controller="DbBus" asp-action="Index">岗位管理</a></li>
                <li class="active">删除岗位信息</li>

            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->

<h3>你确定要删除吗?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BuName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="BuId" />
        <input type="submit" value="删除" class="btn btn-lg btn-danger"/> |
        <a asp-action="Index">职位管理</a>
    </form>
</div>

Views/DbBus/Details.cshtml
@model WebApplication8.Models.DbBu
@{
    Layout = "_Layout_admin";
}
@{
    ViewData["Title"] = "Details";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">系统管理</a>
                </li>
                <li><a asp-area="" asp-controller="DbBus" asp-action="Index">岗位管理</a></li>
                <li class="active">岗位信息详情</li>

            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BuName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BuId">修改</a> |
    <a asp-action="Index">职位管理</a>
</div>

Views/DbBus/Edit.cshtml
@model WebApplication8.Models.DbBu
@{
    Layout = "_Layout_admin";
}
@{
    ViewData["Title"] = "Edit";
}


<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">系统管理</a>
                </li>
                <li><a asp-area="" asp-controller="DbBus" asp-action="Index">岗位管理</a></li>
                <li class="active">编辑岗位信息</li>

            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BuId" />
            <div class="form-group">
                <label asp-for="BuName" class="control-label"></label>
                <input asp-for="BuName" class="form-control" />
                <span asp-validation-for="BuName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="保存" class="btn btn-lg btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">职位管理</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/DbBus/Index.cshtml
@model IEnumerable<WebApplication8.Models.DbBu>
@{
    Layout = "_Layout_admin";
}
@{
    ViewData["Title"] = "Index";
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs ace-save-state" id="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="#">Home</a>
                </li>

                <li>
                    <a href="#">系统管理</a>
                </li>
                <li  class="active">岗位管理</li>
       

            </ul><!-- /.breadcrumb -->

            <div class="nav-search" id="nav-search">
                <form class="form-search">
                    <span class="input-icon">
                        <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                        <i class="ace-icon fa fa-search nav-search-icon"></i>
                    </span>
                </form>
            </div><!-- /.nav-search -->
        </div>


    </div><!-- /.row -->
</div><!-- /.page-content -->



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BuName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BuName)
                </td>
                <td>
                  


                    <a asp-action="Details" asp-route-id="@item.BuId" class="tooltip-info" data-rel="tooltip" title="Details">
                        <span class="blue">
                            <i class="ace-icon fa fa-search-plus bigger-120"></i>
                        </span>
                    </a>



                    <a asp-action="Edit" asp-route-id="@item.BuId" class="tooltip-success" data-rel="tooltip" title="Edit">
                        <span class="green">
                            <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                        </span>
                    </a>



                    <a asp-action="Delete" asp-route-id="@item.BuId" class="tooltip-error" data-rel="tooltip" title="Delete">
                        <span class="red">
                            <i class="ace-icon fa fa-trash-o bigger-120"></i>
                        </span>
                    </a>



                </td>
            </tr>
        }
    </tbody>
</table>
<p>
    <a asp-action="Create">添加职位</a>
</p>